//
//  NSArray+Functional.h
//
//  Created by Andrew Zamler-Carhart on 12/7/19.
//

#import <Foundation/Foundation.h>

@interface NSArray (Functional)

// Returns a new array by calling the block a
// given number of times and returning the results.
+ (NSArray *) generate:(id(^)(void))block
                 count:(int)count;

// Generates an array of numbers in the given range.
+ (NSArray *) numbersInRange:(NSRange)range;

// Performs the block on each object in the array.
- (void) each:(void(^)(id object))block;

// Returns true if the block returns true for every object in the array.
- (BOOL) every:(BOOL(^)(id object))block;

// Returns true if the block returns true for any object in the array.
- (BOOL) any:(BOOL(^)(id object))block;

// Returns true if the array contains all of the objects.
- (BOOL) containsObjects:(NSArray *)objects;

// Returns the first object in the array for which the block returns true.
- (id) find:(BOOL(^)(id object))block;

// Calls the block on every object in the array
// and returns an array of the results.
- (NSArray *) map:(id(^)(id object))block;

// Calls the block on every object in the array along
// with the index and returns an array of the results.
- (NSArray *) indexedMap:(id(^)(NSUInteger index, id object))block;

// Creates a marrix that is the result of calling the block
// on every combination of objects from this and the other array.
- (NSArray *) matrixMap:(id(^)(id object1, id object2))block
                objects:(NSArray *)objects;

// Returns a matrix that is the result of calling the block
// with every combination of two objects from the array.
// Equivalent to passing self to matrix:objects:.
- (NSArray *) squareMap:(id(^)(id object1, id object2))block;

// Given a nested array, returns a nested array of
// the results of calling the block on each item.
- (NSArray *) nestedMap:(id(^)(id object))block;

// Given an array of blocks, returns an array of arrays
// generated by calling all of the blocks on each object.
- (NSArray *) multiMap:(NSArray *)blocks;

// Returns an array by looking up each object in the dictionary
// and replacing it with the corresponding value.
- (NSArray *) replace:(NSDictionary *)dict;

// Returns an array consisting of all the objects
// in the array for which the block returns true.
- (NSArray *) filter:(BOOL(^)(id object))block;

// Returns an array consisting of all the objects
// in the array for which the block returns false.
- (NSArray *) remove:(BOOL(^)(id object))block;

// Returns just the objects that are in the other array.
- (NSArray *) filterObjectsIn:(NSArray *)objects;

// Returns just the objects that are not in the other array.
- (NSArray *) removeObjectsIn:(NSArray *)objects;

// Reduces the array using a block. Each time the block is called,
// it is passed the accumulator value and one object from the array,
// and returns a new accumulator value. The function takes an initial
// value and returns the final accumulator value. If the initial value
// is nil, uses the first value as the initial value.
- (id) reduce:(id(^)(id acc, id object))block;
- (id) reduce:(id(^)(id acc, id object))block
      initial:(id)initial;

// Returns an array sorted using the compare: selector.
- (NSArray *) sort;

// Returns an array sorted using the comparator block.
// Just an alias for the sortedArrayUsingComparator: method.
- (NSArray *) sort:(NSComparator)block;

// Returns an array sorted by calling the block on
// each object and comparing the resulting integers.
- (NSArray *) sortBy:(NSUInteger(^)(id object))block;

// Returns an array with the objects reversed.
- (NSArray *) reverse;

// Returns an array with only the unique objects from the array.
// The order of the results is undefined.
- (NSArray *) unique;

// Returns an initial slice of the array with a length up to the limit.
- (NSArray *) limit:(int)limit;

// Joins the items in the array using commas.
- (NSString *) join;

// Joins the items in the array using the separator.
// Just an alias for the componentsJoinedByString: method.
- (NSString *) join:(NSString *)separator;

// Returns a random object from the array.
- (id) randomObject;

// Returns an array with the objects in a random order.
- (NSArray *) shuffle;

// Interleaves items with objects from the other array.
- (NSArray *) zip:(NSArray *)objects;

// Returns the items in the array, flattening any arrays.
- (NSArray *) flatten;

// Alias for arrayByAddingObjectsFromArray:.
- (NSArray *) concat:(NSArray *)objects;

@end

@interface NSObject (RandomObject)

- (NSComparisonResult) randomCompare: (NSObject *) object;

@end

@interface NSString (StringAdditions)

- (BOOL) contains: (NSString *) string;

@end


